### ISSUE TITLE
Signed successfully and encountered an error, failed to trigger the bot

### ISSUE THREAD

**Issue by MikeH1999** [fidlabs/allocator-tooling#77] opened 2024-10-07 07:15 UTC
![image](https://github.com/user-attachments/assets/a7d13972-bc0b-4d80-8703-3d0e0d7289e3)

https://github.com/MikeH1999/RFfil/issues/43

![image](https://github.com/user-attachments/assets/2f1039b9-8a0a-49f8-b638-f8d439f674cc)

datacap has been deducted. The last signature trigger was actually successful, but the page was not updated and the LDN did not return any information about the successful signature.

https://filfox.info/en/message/bafy2bzacedcknu6vqfmsmtpcaglv7f4zkrrqnwkxe6af2gqz3jkg5inylrh3u?t=1

**Comment by kacperzuk-neti** [comment] 2024-10-07 08:00
Thank you for reporting. Please don't issue any datacap for this client until we investigate and provide a fix. Should be done today.

**Comment by Lind111** [comment] 2024-10-08 01:27
https://github.com/Lind111/EF/issues/27
Mine seems to have the same problem, help with that, thanks! 
@kacperzuk-neti

**Comment by Filip-L** [comment] 2024-10-08 09:32
Hey @MikeH1999 , the solution to your problem is ready.
I prepared a valid JSON file for your application and created a new PR in your repo.
Please do the following steps:
1. Select invalid PR ([#48](https://github.com/MikeH1999/RFfil/pull/48)) on the PR list (checkbox on the left of PR name)
2. Click on the "Mark as" dropdown and click "Closed"
3. Merge PR https://github.com/MikeH1999/RFfil/pull/49

**Comment by Filip-L** [comment] 2024-10-08 12:47
Hey @Lind111,  the solution to your problem is ready.
I prepared a valid JSON file for your application and created a new PR in your repo. Please merge the PR at https://github.com/Lind111/EF/pull/31/files. After that, I will trigger cache renewal on your repo.

**Comment by MikeH1999** [comment] 2024-10-09 04:47
> Hey @MikeH1999 , the solution to your problem is ready. I prepared a valid JSON file for your application and created a new PR in your repo. Please do the following steps:
> 
> 1. Select invalid PR ([#48](https://github.com/MikeH1999/RFfil/pull/48)) on the PR list (checkbox on the left of PR name)
> 2. Click on the "Mark as" dropdown and click "Closed"
> 3. Merge PR [Datacap for Shenyang Dongya Medical Research Institute Co. MikeH1999/RFfil#49](https://github.com/MikeH1999/RFfil/pull/49)

@Filip-L  Would you please check to see if I'm doing this correctly?

**Comment by Filip-L** [comment] 2024-10-09 10:14
@MikeH1999 Unfortunately, while you did it correctly initially, after the merge, I should have triggered cache renewal for your applications. However, I wasn't able to do this because you reverted the changes. I prepared the valid JSON again, created PR into your repository which was automatically merged, and ran the cache renewal for your applications. The application history should be correct now. https://allocator.tech/application/MikeH1999/RFfil/f146jbsccg3cdoo4tbpkh242s4lpfnfivsg2ftoda

**Comment by MikeH1999** [comment] 2024-10-09 10:18
@Filip-L  That's great. Thanks.

**Comment by kacperzuk-neti** [comment] 2024-10-09 10:21
Root cause issue was resolved and missing allocations were added to affected allocators. Closing the issue.
Please open a new issue if there's anything more needed.

**Closed as completed by kacperzuk-neti** 2024-10-09 10:21 UTC
Labels: bug

**Comment by Lind111** [comment] 2024-10-18 03:25
@kacperzuk-neti @Filip-L Have a new question not sure if this is causing it?Can you help look at it?
![image](https://github.com/user-attachments/assets/42698cbc-702b-416d-8770-84d3388b0cca)
https://github.com/Lind111/EF/issues/27

**Comment by kacperzuk-neti** [comment] 2024-10-21 09:49
@Lind111 Let's track this new issue in https://github.com/fidlabs/allocator-tooling/issues/80
