### ISSUE TITLE
lotus failed to sign due to a glitch

### ISSUE THREAD

**Issue by MikeH1999** [fidlabs/allocator-tooling#47] opened 2024-05-16 12:41 UTC
![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/57bad47e-6e31-4eb4-b8e9-ad0ed817b4d9)
lotus failed to sign due to a glitch

**Comment by kacperzuk-neti** [comment] 2024-11-26 11:11
Closing, as long time has passed, this no longer happens and we don't have enough data to pinpoint what was the cause in this exact situation.
If this still happens in some way, please open a fresh issue and we'll take a look immediately.

**Closed by kacperzuk-neti** 2024-11-26 11:11 UTC
