### ISSUE TITLE
NO  bot CID Checker report 

### ISSUE THREAD

**Issue by Chuangshi1** [fidlabs/allocator-tooling#61] opened 2024-06-17 08:34 UTC
https://github.com/Chuangshi1/Genesis/issues/30
https://github.com/Chuangshi1/Genesis/issues/6
![image](https://github.com/fidlabs/allocator-tooling/assets/112937825/405b6cc0-fcd8-44ab-8260-ae791dc3c0f8)
![image](https://github.com/fidlabs/allocator-tooling/assets/112937825/4204284f-8ba2-45ce-97c5-f30e97198db3)
This is allocator-genesis.
There are 5 applications in my pathway. The two applications can't show the report. But when i contact with the client, they all seal normally. And they post the picture of SP retrieval  situation.
About the  https://github.com/Chuangshi1/Genesis/issues/6  I just stop allocating DC to them.
https://github.com/Chuangshi1/Genesis/issues/30   It is the first round, i don't know if i can send DC to them next.
hope you can help us to check the report problem. Thanks.

**Comment by kacperzuk-neti** [comment] 2024-06-17 12:10
Looks like two separate problems, we'll look into it.

**Comment by Chuangshi1** [comment] 2024-06-18 01:11
@kacperzuk-neti  Thank you so much. Hope it can be fixed soon.

**Comment by kacperzuk-neti** [comment] 2024-06-18 10:05
@Chuangshi1 please check again for https://github.com/Chuangshi1/Genesis/issues/30 , it should be able to find the application data now.

**Comment by Chuangshi1** [comment] 2024-06-19 01:23
> @Chuangshi1 please check again for [Chuangshi1/Genesis#30](https://github.com/Chuangshi1/Genesis/issues/30) , it should be able to find the application data now.

![image](https://github.com/fidlabs/allocator-tooling/assets/112937825/dad24c03-7eca-4aa1-8ec0-b198d5a36bc4)
@kacperzuk-neti  It looks like still can't find the data.

**Comment by kacperzuk-neti** [comment] 2024-06-20 12:31
Sorry for that. Looks like even though the data was fixed in the API CID Checker uses, internal cache was still breaking things. The cache was cleared and it succeded in generating report ( https://check.allocator.tech/report/Chuangshi1/Genesis/issues/30/1718886646300.md ). Go ahead and try triggering it yourself.

**Comment by Chuangshi1** [comment] 2024-06-21 06:44
> Sorry for that. Looks like even though the data was fixed in the API CID Checker uses, internal cache was still breaking things. The cache was cleared and it succeded in generating report ( https://check.allocator.tech/report/Chuangshi1/Genesis/issues/30/1718886646300.md ). Go ahead and try triggering it yourself.

@kacperzuk-neti Thank you so much. It works now. But the datacap used always show loading. As an allocator, i can't approve DC to the client. And only this application occurs like that. https://github.com/Chuangshi1/Genesis/issues/30
![image](https://github.com/fidlabs/allocator-tooling/assets/112937825/110fc515-1cc4-43d1-a98f-d7a19cd34f89)

**Comment by kacperzuk-neti** [comment] 2024-06-21 10:47
This is caused by invalid value in "Weekly Allocation" field. It should be `500TiB`. `500T` is ambiguous, as it could mean `500TB`.

**Comment by kacperzuk-neti** [comment] 2024-07-01 11:18
@Chuangshi1  Is there any other problem left to resolve as part of this issue?

**Comment by Chuangshi1** [comment] 2024-07-02 01:49
> @Chuangshi1 Is there any other problem left to resolve as part of this issue?

no problem. Thanks a lot.

**Closed as completed** 2024-07-02 08:26 UTC
