### ISSUE TITLE
Robot not working

### ISSUE THREAD

**Issue by MikeH1999** [fidlabs/allocator-tooling#24] opened 2024-03-28 11:58 UTC
https://github.com/MikeH1999/RFfil/issues/15

but `checker:manualTrigger` is ok

![image](https://github.com/fidlabs/allocator-tooling/assets/149572051/c5864677-c1c0-4811-aff3-3ba6c99316ba)

**Comment by willscott** [comment] 2024-03-28 12:03
Look in the action run associated with the issue:
https://github.com/MikeH1999/RFfil/actions/runs/8466836976/job/23196456589

the robot says:
`Application issue f1uci7zkbdvscvu5mklxwwafkqqn7qo7rwc6rfoxi already exists`

because this is a duplicate of #10 there will not be an additional PR made

**Closed by willscott** 2024-03-28 12:03 UTC
