### ISSUE TITLE
some bugs about storing duplicate data

### ISSUE THREAD

**Issue by TOPPOOL-LEE** [fidlabs/allocator-tooling#88] opened 2024-10-31 05:29 UTC
Several LDNs in toppool have bugs storing duplicate data.

https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/issues/22
<img width="935" alt="WX20241031-132540@2x" src="https://github.com/user-attachments/assets/d84135d0-0219-4a46-be1e-b7df696506b9">
https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/issues/20
<img width="1000" alt="WX20241031-132645@2x" src="https://github.com/user-attachments/assets/d58b6ece-c8f5-4644-bbd8-45ae814e00a0">
https://github.com/TOPPOOL-LEE/Allocator-Pathway-TOP-POOL/issues/18
<img width="931" alt="WX20241031-132738@2x" src="https://github.com/user-attachments/assets/b7942d0a-7d8c-432a-a7ff-139e3d9502de">

**Comment by kacperzuk-neti** [comment] 2024-10-31 07:29
This is a known issue with the data provider, tracked in https://github.com/fidlabs/allocator-tooling/issues/73 . Fix is being worked on.

**Comment by kacperzuk-neti** [comment] 2024-11-06 10:33
Closing as this is a duplicate of #73 - please follow #73 for updates.

**Closed as completed by kacperzuk-neti** 2024-11-06 10:33 UTC
Labels: dmob-data-issue
