### ISSUE TITLE
Bot and label don't update after signed

### ISSUE THREAD

**Issue by CloudX-Lab** [fidlabs/allocator-tooling#90] opened 2024-11-04 07:40 UTC
We tried to sign for our client. But there's no bot - request approved
![image](https://github.com/user-attachments/assets/1d461246-cab8-4596-a359-dd3658bc4d13)
(This bot didn't showed on application. )

Since there was no bot update on application, we tried to sign twice. Then we noticed that the amount of datacap was already allocated. 

See this [application](https://github.com/CloudX-Lab/filecion/issues/21).
The same problem happens on [application](https://github.com/CloudX-Lab/filecion/issues/17).

**Comment by kacperzuk-neti** [comment] 2024-11-04 07:54
Thanks for the report. I'll fix the state of the applications manually.

In the meantime, can you tell me what exactly happened on screen after approving the allocation on Ledger device? We have a known issue that can cause this, but I need to confirm.

**Comment by kacperzuk-neti** [comment] 2024-11-04 07:58
[internal note]

List of onchain allocations that are missing on allocator.tech:
* https://beryx.io/fil/mainnet/txs/bafy2bzacecofzeymubif4zlnelcrlre76mvouzyhk4o2unpzpsxfr6y4uub5y?tab=internalMessages
    * CID: bafy2bzacecofzeymubif4zlnelcrlre76mvouzyhk4o2unpzpsxfr6y4uub5y
    * Client: `f1naljnu2ieqmdeh4jbxobcqbzwqri24zfpdczxby`
    * Amount: `512TiB`
* https://beryx.io/fil/mainnet/txs/bafy2bzaceam6xcuacvxvy4hg4zpw4zobfazjxdszwe3yqmtbkd6advu2rk2h4?tab=internalMessages
    * CID: `bafy2bzaceam6xcuacvxvy4hg4zpw4zobfazjxdszwe3yqmtbkd6advu2rk2h4`
    * Client: `f1naljnu2ieqmdeh4jbxobcqbzwqri24zfpdczxby`
    * Amount: `512TiB`
* https://beryx.io/fil/mainnet/txs/bafy2bzacebj5vllckwqpke2v5roxccsgey25xwxo44nu2ajvcpnaw3elguhac?tab=internalMessages
    * CID: `bafy2bzacebj5vllckwqpke2v5roxccsgey25xwxo44nu2ajvcpnaw3elguhac`
    * Client: `f12cxxx4ruxcisre52awaohwfgxq3pjtm4efm3v3q`
    * Amount: `512TiB`

**Comment by kacperzuk-neti** [comment] 2024-11-04 08:16
State of applications on allocator.tech was updated to reflect state on chain.

@CloudX-Lab can you tell me what exactly happened on computer screen after approving the allocation on Ledger device?

**Comment by CloudX-Lab** [comment] 2024-11-04 08:17
https://github.com/CloudX-Lab/filecion/issues/21
![image](https://github.com/user-attachments/assets/b53b06f0-34a7-4f08-a5eb-09b2f52500ac)
We just have this page. Can not get the screenshot from ledger now.

**Comment by kacperzuk-neti** [comment] 2024-11-04 08:21
@CloudX-Lab but do you remember what happened during the signing process? Normal flow is:
1. You click propose, the page gets dark and there's a message asking you to review & approve transaction on the ledger
2. After approving on ledger, page stays dark for a few minutes and the message changes to something like "Verifying, this can take a few minutes, don't close this window"
3. After a few minutes the page refreshes, there's no longer dark overlay and the application state should say granted (this obviously didn't happen)

What was different in your case? Did it show any errors on the page after approving on ledger?

**Comment by CloudX-Lab** [comment] 2024-11-04 08:29
@kacperzuk-neti I remembered that the last page on ledger shows error. But I didn't take a screenshot.

**Comment by kacperzuk-neti** [comment] 2024-11-04 08:35
Ok, so we'll assume that this was caused by the known issue. We're working on fixing this so that it's impossible for the bot to miss things.

For now, please:
* make sure you keep the page open until the `this can take a few minutes, don't close this window` message disappears,
* if approved on ledger, assume that it was executed on chain, even if there's no message from the bot - open an issue here if bot doesn't reply.

**Closed as completed by kacperzuk-neti** 2024-11-04 08:35 UTC
Labels: bug
