### ISSUE TITLE
Robot statistics error

### ISSUE THREAD

**Issue by nike-mp** [fidlabs/allocator-tooling#81] opened 2024-10-26 03:39 UTC
https://github.com/NDLABS-Leo/Allocator-Pathway-ND-CLOUD/issues/39
![WechatIMG24857](https://github.com/user-attachments/assets/07a67e02-f163-4a1e-a5c4-f72a677780d9)

First, bot appeared 5 days after DC allocation.
Second, bot statistics were wrong, showing a lot of duplicate storage data. We used 200T in total, but bot only counted 50T.

Thank you for helping us update the data.

**Comment by kacperzuk-neti** [comment] 2024-10-28 11:17
> First, bot appeared 5 days after DC allocation.

This was fixed already by the data provider. New data should now be synced every 2 hours.

> Second, bot statistics were wrong, showing a lot of duplicate storage data.

This is a known issue with the data provider, tracked in https://github.com/fidlabs/allocator-tooling/issues/73

> We used 200T in total, but bot only counted 50T.

Is all the data sealed already or is it still being onboarded by storage providers?

**Comment by nike-mp** [comment] 2024-10-29 02:28
All data is sealed, thank you for your efforts

**Comment by kacperzuk-neti** [comment] 2024-10-29 13:27
@nike-mp our data provider has identified the cause of missing 150T of deal data - they're working on a fix.

**Comment by nike-mp** [comment] 2024-10-30 03:04
thanks

**Comment by nike-mp** [comment] 2024-10-30 09:44
The alloctor  can't sign for me, can you help me check?
<img width="689" alt="381454122-778127c6-1191-4e98-b603-5c0c54288131" src="https://github.com/user-attachments/assets/1f608d28-c8fd-4753-aee8-66be784ca723">

**Comment by kacperzuk-neti** [comment] 2024-10-30 09:46
> The alloctor can't sign for me, can you help me check?

@nike-mp please open a new issue for this to keep discussions organized.

**Comment by kacperzuk-neti** [comment] 2024-10-31 14:20
> @nike-mp our data provider has identified the cause of missing 150T of deal data - they're working on a fix.

The missing 150TiB issue is fixed - you should now see all 200TiB in new reports.
Most of the duplicate deal issue was also mitigated, but not all of it - you'll still see a few % of duplicate data reported - our data provider is still working on a complete fix for that.

> The alloctor can't sign for me, can you help me check?

This screenshot only means that you've used all of your datacap and has none left. This shouldn't cause any issues for the allocator, they should be able to allocate more datacap to you. If that's not the case, ask them to open a new issue describing what's wrong exactly: https://github.com/fidlabs/allocator-tooling/issues/new


As the core issue (missing 150T data) is fixed, I'll close this issue now. Feel free to open a new issue at any time or leave a comment on https://github.com/fidlabs/allocator-tooling/issues/73 if it's about duplicate data.

**Closed as completed by kacperzuk-neti** 2024-10-31 14:20 UTC
Labels: dmob-data-issue
